### ISSUE TITLE
Macro example doesn't compile

### ISSUE THREAD

**Issue by zaach** [puffnfresh/roy#104]
Here's the compiler error:

```
Compiling to: 1

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object 1 has no method 'accept'
    at /Users/zach/repos/roy/src/typeinference.js:139:17
    at Object.visitReplacement (/Users/zach/repos/roy/src/typeinference.js:279:20)
    at [object Object].accept (/Users/zach/repos/roy/src/nodes.js:280:26)
    at /Users/zach/repos/roy/src/typeinference.js:139:17
    at /Users/zach/repos/roy/src/typeinference.js:225:24
    at Array.map (native)
    at Function.map (/Users/zach/repos/roy/node_modules/underscore/underscore.js:93:56)
    at Object.visitCall (/Users/zach/repos/roy/src/typeinference.js:224:27)
    at [object Object].accept (/Users/zach/repos/roy/src/nodes.js:177:26)
    at /Users/zach/repos/roy/src/typeinference.js:139:17
```

`data.roy` and `option.roy` were also giving me errors.

**Comment by puffnfresh** [comment]
Thanks!

The `data.roy` and `option.roy` examples are more targeted towards the http://roy.brianmckenna.org/ website - where the prelude isn't defined. I added a `-p` flag to use instead of `-r` if you don't want to include the prelude.
