### ISSUE TITLE
unexpected THEN

### ISSUE THREAD

**Issue by gregwebs** [puffnfresh/roy#113]
``` javascript
if window.location.href.match /localhost/ then
  console.log "local"
else
  console.log "remote"
```

```
/home/gweber/proj/js/roy/src/parser.js:282
    throw new Error(str);
          ^
Error: Parse error on line 2: Unexpected 'THEN'
    at Object.parseError (/home/gweber/proj/js/roy/src/parser.js:282:11)
    at Object.parse (/home/gweber/proj/js/roy/src/parser.js:358:22)
    at /home/gweber/proj/js/roy/src/compile.js:373:22
    at Socket.<anonymous> (/home/gweber/proj/js/roy/src/compile.js:576:25)
    at Socket.emit (events.js:61:17)
    at Socket._onReadable (net.js:658:51)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```

**Comment by gregwebs** [comment]
it looks like Roy does not support regex literals. I can change this to:

``` javascript
if (window.location.href.match 'localhost') then
```

This is still slightly unsatisfactory because it requires parens - that is probably the same issue as the match/case bug I opened up.

However, this error message should still be improved.

**Comment by puffnfresh** [comment]
Unnecessary parens removed in 8f68d3f46fde81d9ab4d501c1d949362bd2322cc
