### ISSUE TITLE
installation fails on Windows

### ISSUE THREAD

**Issue by nponeccop** [puffnfresh/roy#137]
The spawning probably can be avoided altogether:

```
> roy@0.1.5 install C:\Users\Admin\Desktop\mtbroker\node_modules\roy
> node src/grammar.js && node src/typegrammar.js


npm ERR! Error: spawn ENOTSUP
npm ERR!     at errnoException (child_process.js:483:11)
npm ERR!     at ChildProcess.spawn (child_process.js:446:11)
npm ERR!     at Object.spawn (child_process.js:342:9)
npm ERR!     at spawn (C:\Program Files\nodejs\node_modules\npm\lib\utils\exec.j
s:118:22)
npm ERR!     at exec (C:\Program Files\nodejs\node_modules\npm\lib\utils\exec.js
:50:12)
npm ERR!     at Array.0 (C:\Program Files\nodejs\node_modules\npm\lib\utils\life
cycle.js:146:5)
npm ERR!     at EventEmitter._tickCallback (node.js:192:40)
npm ERR! You may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR!
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "roy"
npm ERR! cwd C:\Users\foo\Desktop\bar
npm ERR! node -v v0.6.16
npm ERR! npm -v 1.1.19
npm ERR! syscall spawn
npm ERR! code ENOTSUP
npm ERR! message spawn ENOTSUP
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\foo\Desktop\bar\npm-debug.log
npm not ok
```

**Comment by TheDet** [comment]
I had this error too ,but finally managed somehow to install roy on win7 as well as on win xp.
It seems to have nothing to do with roy, but with npm resp. Node installation.

I installed it, standing in the node installation folder, manually with

> npm install roy

HTH
Det

**Comment by joneshf** [comment]
Installation seems to work on win7/8 as of late.
