### ISSUE TITLE
Install from source fails on OSX

### ISSUE THREAD

**Issue by g-k** [puffnfresh/roy#154]
For me at least, `source-map` isn't exporting anything. If this is a problem with a dependency version changing, `npm shrinkwrap` might help.

```
~/src - [master●] » node -v
v0.6.21-pre
~/src - [master●] » npm -v
1.1.21
~/src - [master●] » git clone git://github.com/pufuwozu/roy.git
Cloning into 'roy'...
remote: Counting objects: 1845, done.
remote: Compressing objects: 100% (790/790), done.
remote: Total 1845 (delta 1058), reused 1782 (delta 1000)
Receiving objects: 100% (1845/1845), 443.14 KiB | 42 KiB/s, done.
Resolving deltas: 100% (1058/1058), done.
~/src - [master●] » cd roy
src/roy - [master] » npm install --registry=http://registry.npmjs.org/
npm http GET http://registry.npmjs.org/jison/0.2.7
npm http GET http://registry.npmjs.org/source-map/0.1.0
...
├── connect@2.4.6 (fresh@0.1.0, pause@0.0.1, bytes@0.1.0, cookie@0.0.4, crc@0.2.0, debug@0.7.0, formidable@1.0.11, qs@0.5.1, send@0.0.4)
├── prompt@0.1.12 (pkginfo@0.2.3, winston@0.5.11)
└── nodeunit@0.7.4 (tap@0.3.1)
src/roy - [master] » npm prune
src/roy - [master] » make
./node_modules/.bin/grunt
Running "jison:./lib/typeparser.js" (jison) task
Processing grammar.
$accept(0)
...
transitions ->  {}
314 states.
Building lookahead grammar.
Computing lookaheads.
Building parse table.
Done.

Running "lint:src" (lint) task
Lint free.

Running "jasmine:src" (jasmine) task
......................

Finished in 0.722 seconds
22 tests, 34 assertions, 0 failures


Running "rigger:roy.js" (rigger) task

Running "min:roy-min.js" (min) task
File "roy-min.js" created.
Uncompressed size: 283069 bytes.
Compressed size: 47810 bytes gzipped (152596 bytes minified).

Done, without errors.
src/roy - [master] » ./roy
Roy: Small functional language that compiles to JavaScript
Brian McKenna <brian@brianmckenna.org> (http://brianmckenna.org/)
:? for help
roy> %                                                                                                                                                                                                  src/roy - [master] » ./roy -r examples/helloworld.roy

/Users/gregg/src/roy/src/compile.js:817
        var sourceMap = new SourceMapGenerator({file: path.basename(outputPath
                        ^
TypeError: undefined is not a function
    at /Users/gregg/src/roy/src/compile.js:817:25
    at Array.forEach (native)
    at Function.<anonymous> (/Users/gregg/src/roy/node_modules/underscore/underscore.js:74:11)
    at Object.main (/Users/gregg/src/roy/src/compile.js:803:7)
    at Object.<anonymous> (/Users/gregg/src/roy/roy:2:26)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
src/roy - [master] » git log -1 --oneline
4677612 Merge pull request #152 from miikka/master
src/roy - [master] » npm list
roy@0.1.5 /Users/gregg/src/roy
├─┬ grunt@0.3.15 
│ ├── async@0.1.22 
│ ├── colors@0.6.0-1 
│ ├─┬ connect@2.4.6 
│ │ ├── bytes@0.1.0 
│ │ ├── cookie@0.0.4 
│ │ ├── crc@0.2.0 
│ │ ├── debug@0.7.0 
│ │ ├── formidable@1.0.11 
│ │ ├── fresh@0.1.0 
│ │ ├── pause@0.0.1 
│ │ ├── qs@0.5.1 
│ │ └─┬ send@0.0.4 
│ │   ├── mime@1.2.6 
│ │   └── range-parser@0.0.4 
│ ├── dateformat@1.0.2-1.2.3 
│ ├─┬ glob-whatev@0.1.8 
│ │ └─┬ minimatch@0.2.9 
│ │   ├── lru-cache@2.0.4 
│ │   └── sigmund@1.0.0 
│ ├─┬ gzip-js@0.3.1 
│ │ ├── crc32@0.2.2 
│ │ └── deflate-js@0.2.2 
│ ├── hooker@0.2.3 
│ ├─┬ jshint@0.5.9 
│ │ ├── argsparser@0.0.6 
│ │ └─┬ minimatch@0.2.9 
│ │   ├── lru-cache@2.0.4 
│ │   └── sigmund@1.0.0 
│ ├─┬ nodeunit@0.7.4 
│ │ └─┬ tap@0.3.1 
│ │   ├── buffer-equal@0.0.0 
│ │   ├── deep-equal@0.0.0 
│ │   ├─┬ difflet@0.2.3 
│ │   │ ├── charm@0.0.8 
│ │   │ └── traverse@0.6.3 
│ │   ├── inherits@1.0.0 
│ │   ├── mkdirp@0.3.4 
│ │   ├─┬ nopt@2.0.0 
│ │   │ └── abbrev@1.0.3 
│ │   ├─┬ runforcover@0.0.2 
│ │   │ └─┬ bunker@0.1.2 
│ │   │   └─┬ burrito@0.2.12 
│ │   │     ├── traverse@0.5.2 
│ │   │     └── uglify-js@1.1.1 
│ │   ├── slide@1.1.3 
│ │   └── yamlish@0.0.5 
│ ├─┬ nopt@1.0.10 
│ │ └── abbrev@1.0.3 
│ ├─┬ prompt@0.1.12 
│ │ ├── pkginfo@0.2.3 
│ │ └─┬ winston@0.5.11 
│ │   ├── eyes@0.1.8 
│ │   ├─┬ loggly@0.3.11 
│ │   │ ├── request@2.9.203 
│ │   │ └── timespan@2.2.0 
│ │   └── stack-trace@0.0.6 
│ ├── semver@1.0.14 
│ ├─┬ temporary@0.0.4 
│ │ └── package@1.0.1 
│ ├── uglify-js@1.3.4 
│ ├── underscore@1.2.4 
│ └── underscore.string@2.1.1 
├─┬ jasmine-node@1.0.26 
│ ├── coffee-script@1.4.0 
│ ├── jasmine-reporters@0.2.1 
│ ├── requirejs@2.1.1 
│ ├── underscore@1.4.2 
│ └── walkdir@0.0.5 
├── jison@0.2.7 
├─┬ rigger@0.3.19 
│ ├── async@0.1.22 
│ ├── debug@0.7.0 
│ ├─┬ getit@0.2.1 
│ │ ├── mkdirp@0.3.4 
│ │ └─┬ request@2.11.4 
│ │   ├─┬ form-data@0.0.3 
│ │   │ ├── async@0.1.9 
│ │   │ └─┬ combined-stream@0.0.3 
│ │   │   └── delayed-stream@0.0.5 
│ │   └── mime@1.2.7 
│ ├─┬ squirrel@0.1.1 
│ │ └── read@0.1.1 
│ └── underscore@1.3.3 
├─┬ source-map@0.1.0 
│ └── requirejs@2.1.1 
├── underscore@1.2.0 
└── unicode-categories@0.9.0 

src/roy - [master] » 
```

**Comment by dbousamra** [comment]
I also have this issue.
