### ISSUE TITLE
Sole identifiers cause escodegen error.

### ISSUE THREAD

**Issue by joneshf** [puffnfresh/roy#178]
Any identifier on a line by itself causes this error.  If you're in the repl this can be easily tested

```
roy> let a = 3
roy> a
Error: Unknown statement type: Identifier
    at generateStatement (/home/joneshf/programming/roylang/node_modules/escodegen/escodegen.js:1886:19)
    at generateStatement (/home/joneshf/programming/roylang/node_modules/escodegen/escodegen.js:1824:21)
    at Object.generate (/home/joneshf/programming/roylang/node_modules/escodegen/escodegen.js:1987:22)
    at compile (/home/joneshf/programming/roylang/src/compile.js:916:28)
    at Interface.nodeRepl (/home/joneshf/programming/roylang/src/compile.js:1075:28)
    at Interface.EventEmitter.emit (events.js:96:17)
    at Interface._onLine (readline.js:200:10)
    at Interface._line (readline.js:518:8)
    at Interface._ttyWrite (readline.js:736:14)
    at ReadStream.onkeypress (readline.js:97:10)

```

The tree that is created is:

``` json
{
    "type": "Program",
    "body": [
        {
            "type": "Identifier",
            "name": "a"
        }
    ]
}

```

I haven't looked at escodegen too deeply, can a body have just an identifier like that, or does it need to be inside of something else?

**Comment by cassiemeharry** [comment]
Fixed by #179
