### ISSUE TITLE
Add support for calling roy from any place

### ISSUE THREAD

**Issue by folone** [puffnfresh/roy#64]
Would like to do such a thing:
I add an env variable `$ROY_HOME`, pointing to the directory, where roy is compiled and add it to `$PATH`. If I then execute `roy` from it's directory, it starts fine. If I do it from any other directory:

```
$  roy
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: ENOENT, no such file or directory 'package.json'
    at Object.openSync (fs.js:228:18)
    at Object.readFileSync (fs.js:119:15)
    at Object.main (/home/georgii/workspace/roy/src/compile.js:462:23)
    at Object.<anonymous> (/home/georgii/workspace/roy/roy:2:26)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.0 (module.js:470:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

**Comment by paulmillr** [comment]
With my patch, you'll need to do `npm link` if you want to use roy from github (instead of stable roy from npm). It automatically creates all binaries.

**Comment by paulmillr** [comment]
Oh, my bad. `npm link` works with current `master`. Patch is not needed.

**Comment by folone** [comment]
Thanks for help, this ticket is not needed, sorry for the noise.
