### ISSUE TITLE
Can't compile when accessing properties on strings

### ISSUE THREAD

**Issue by tokland** [puffnfresh/roy#93]
What's the correct way to access properties on strings? I can't seem to make this work:

```
let getLength (s: String) : Number = 
  s.length
console.log (getLength "hello there")
```

I get:

```
Error: Type error: String is not {length: 'bt}
    at /var/abs/local/roy/src/typeinference.js:45:19
    at Object.visitAccess (/var/abs/local/roy/src/typeinference.js:305:17)
    at [object Object].accept (/var/abs/local/roy/src/nodes.js:198:26)
    at /var/abs/local/roy/src/typeinference.js:139:17
    at /var/abs/local/roy/src/typeinference.js:185:24
    at Array.map (native)
    at Function.map (/var/abs/local/roy/node_modules/underscore/underscore.js:100:56)
    at Object.visitFunction (/var/abs/local/roy/src/typeinference.js:184:32)
    at [object Object].accept (/var/abs/local/roy/src/nodes.js:33:26)
    at /var/abs/local/roy/src/typeinference.js:139:17
```

Using 136665929c9. Thanks.

**Comment by puffnfresh** [comment]
This is a problem with Roy's type-system but I'm not sure what the best solution is:
- I don't think it's wise to encode properties like `length` in the type-system for the String and Array types. You could just call `s.length`. But what if a specific engine (or library) provides an extra property we don't know about?
- We could provide native JS functions that call these properties without type-safety. You would have to call `stringLength s`. Would work for extra properties but wouldn't be too nice.

Any other ideas?

**Comment by tokland** [comment]
> I don't think it's wise to encode properties like length in the type-system for the String and Array types.

I agree, it'd be better to have some interface layer in between. 

I just skimmed through the examples of Roy, so I am not sure what the language can or can't do (or is planned to do). Some thoughts about this (I hope not too misleading):

https://gist.github.com/1641425

It would be great to have some batteries include in the form of modules (String, List, Array) with the usual suspects for FP (List.map, List.filter, etc), but I guess that's another subject.
