### ISSUE TITLE
Type-inference error on '!' access

### ISSUE THREAD

**Issue by tokland** [puffnfresh/roy#97]
Shouldn't this work?

```
let double x = 2*x
let f xs g = g (xs ! 0)
console.log (f [1,2,3] double)
```

I get:

```
Error: Type error: [Number] is not {[object Object]: 'by}
    at /var/abs/local/roy/src/typeinference.js:45:19
    at /var/abs/local/roy/src/typeinference.js:56:13
```

Using 8e9614577e.

**Comment by puffnfresh** [comment]
Thanks, works in ebc38fefb7708d1a88d9bcbf3884e98a895b66d2.

**Comment by tokland** [comment]
thanks!
